name: Build Windows

# 1. IL TRIGGER
on:
  push:
    tags:
      - 'w*'


permissions:
  contents: write # Fondamentale: serve per permettere al bot di creare la Release

jobs:
  build_and_release:
    runs-on: windows-latest # Cambia con 'windows-latest' o 'macos-latest' se serve

    steps:
        
      # Scarica il codice del repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # 2. VAI NELLA CARTELLA SPECIFICA E FAI MAKE
      - name: Setup pipeline python
        working-directory: ./src # <--- MODIFICA QUI
        run: |
          make pipeline_python-setup
          
      - name: compile pipeline
        working-directory: ./src
        run: |
          make compile-pipeline

      - name: Clean pipeline python setup
        working-directory: ./src/main
        run: |
          rm -r pediatric_fdopa_pipeline

      - name: Main app python setup
        working-directory: ./src
        run: |
          make main_python-setup

      - name: Compile main app
        working-directory: ./src
        run: |
          make compile-app

      # 3. ZIppa IL CONTENUTO DELLA CARTELLA DI OUTPUT
      - name: Zip the output (FLAT)
        # 1. Ci spostiamo DENTRO la cartella dist
        working-directory: ./src/main/dist
        run: |
          # 2. Creiamo lo zip nel livello superiore (..) cosÃ¬ non si zippa addosso
          zip -r ../GliAAns_${{ github.ref_name }}.zip .

      # 4. PUBBLICA LA RELEASE
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # 3. Il file si trova in src/main (livello superiore rispetto a dist)
          files: ./src/main/GliAAns_${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
